### PR TITLE
Replacing the loop into a Thread wait when running in auto mode.

### PR DESCRIPTION
**Pull request by tuhlmann**
I created this PR because lein sass auto does take up a lot of CPU when I start it.

The directory watch spawns its own Thread to watch for file changes.
Thus the call will immediately return and enter the loop and does a recur
at full speed.

### CODE REVIEW

**Comment by stephanos** [comment]
Thanks, I don't use the plugin anymore (or Leinigen for that matter), so I'll trust you on this :)

**Comment by tuhlmann** [comment]
Yeah, its working for me :)

**Comment by tuhlmann** [comment]
@stephanos I don't have another contact info of you, so I append to this PR.

I have added some flags to be able to switch between sassc and the Ruby sass Gem to the plugin.
Would you want a pull request, or should I maintain the lein-sass fork on my account (as you said you're not using it anymore)?

If so, are there anythings to consider when pushing to clojars, never done that before.

Thanks,
Torsten.

PS: Your server seems offline...

**Comment by stephanos** [comment]
@tuhlmann 
I think a fork is a better idea, especially when talking about JRuby support. The plugin is called lein-sass**c** after all.

About deploying to Clojars, I'm not sure anymore which guide I used, it may have been [this one](https://github.com/technomancy/leiningen/blob/preview/doc/DEPLOY.md). Good luck :)

**Pull request merged**
